In [47]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import make_column_transformer
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline, make_pipeline
from sklearn.tree import DecisionTreeClassifier
from sklearn.impute import SimpleImputer

In [48]:
train_df = pd.read_csv('train.csv')

In [49]:
test_df = pd.read_csv('test.csv')

In [50]:
train_df.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Thayer)  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [52]:
y_train = train_df['Survived']

In [61]:
train_df.drop(['Name', 'PassengerId', 'Cabin', 'Ticket'], axis = 1, inplace = True)

KeyError: "['Name', 'PassengerId', 'Cabin', 'Ticket'] not found in axis"

In [78]:
train_df.head()


Pclass     Sex   Age  SibSp  Parch     Fare Embarked
0       3    male  22.0      1      0   7.2500        S
1       1  female  38.0      1      0  71.2833        C
2       3  female  26.0      0      0   7.9250        S
3       1  female  35.0      1      0  53.1000        S
4       3    male  35.0      0      0   8.0500        S

In [74]:
test_df.head()

Pclass     Sex   Age  SibSp  Parch     Fare Embarked
0       3    male  34.5      0      0   7.8292        Q
1       3  female  47.0      1      0   7.0000        S
2       2    male  62.0      0      0   9.6875        Q
3       3    male  27.0      0      0   8.6625        S
4       3  female  22.0      1      1  12.2875        S

In [79]:
trf1 = make_column_transformer(
    (SimpleImputer(strategy='mean'), [2]),
    (SimpleImputer(strategy='most_frequent'), [6]),
    remainder = 'passthrough')

In [80]:
copy_df = train_df

In [81]:
trf1.fit_transform(train_df)

array([[22.0, 'S', 3, ..., 1, 0, 7.25],
       [38.0, 'C', 1, ..., 1, 0, 71.2833],
       [26.0, 'S', 3, ..., 0, 0, 7.925],
       ...,
       [29.69911764705882, 'S', 3, ..., 1, 2, 23.45],
       [26.0, 'C', 1, ..., 0, 0, 30.0],
       [32.0, 'Q', 3, ..., 0, 0, 7.75]], dtype=object)

In [82]:
copy_df = trf1.fit_transform(copy_df)

In [83]:
copy_df

array([[22.0, 'S', 3, ..., 1, 0, 7.25],
       [38.0, 'C', 1, ..., 1, 0, 71.2833],
       [26.0, 'S', 3, ..., 0, 0, 7.925],
       ...,
       [29.69911764705882, 'S', 3, ..., 1, 2, 23.45],
       [26.0, 'C', 1, ..., 0, 0, 30.0],
       [32.0, 'Q', 3, ..., 0, 0, 7.75]], dtype=object)

In [84]:
trf2 = make_column_transformer(
    (OneHotEncoder(handle_unknown='ignore', drop='first'), [1, 3]),
    remainder='passthrough'
)

In [85]:
copy_df = trf2.fit_transform(copy_df)

In [86]:
copy_df

array([[0.0, 1.0, 1.0, ..., 1, 0, 7.25],
       [0.0, 0.0, 0.0, ..., 1, 0, 71.2833],
       [0.0, 1.0, 0.0, ..., 0, 0, 7.925],
       ...,
       [0.0, 1.0, 0.0, ..., 1, 2, 23.45],
       [0.0, 0.0, 1.0, ..., 0, 0, 30.0],
       [1.0, 0.0, 1.0, ..., 0, 0, 7.75]], dtype=object)

In [89]:
trf3 = make_column_transformer(
    (StandardScaler(), [7]),
    remainder='passthrough'
)

In [90]:
copy_df = trf3.fit_transform(copy_df)

In [91]:
copy_df

array([[-0.5024451714361923, 0.0, 1.0, ..., 3, 1, 0],
       [0.7868452935884461, 0.0, 0.0, ..., 1, 1, 0],
       [-0.4888542575852486, 0.0, 1.0, ..., 3, 0, 0],
       ...,
       [-0.17626323901354432, 0.0, 1.0, ..., 3, 1, 2],
       [-0.04438103794142432, 0.0, 0.0, ..., 1, 0, 0],
       [-0.49237782784290063, 1.0, 0.0, ..., 3, 0, 0]], dtype=object)

In [92]:
pipe = make_pipeline(
    (trf1),
    (trf2),
    (trf3)
)

In [93]:
pipe.fit(train_df)

Pipeline(steps=[('columntransformer-1',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('simpleimputer-1',
                                                  SimpleImputer(), [2]),
                                                 ('simpleimputer-2',
                                                  SimpleImputer(strategy='most_frequent'),
                                                  [6])])),
                ('columntransformer-2',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('onehotencoder',
                                                  OneHotEncoder(drop='first',
                                                                handle_unknown='ignore'),
                                                  [1, 3])])),
                ('columntransformer-3',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('standardscaler',
                                                  StandardScaler(), [7])]))])

In [94]:
train_df = pipe.transform(train_df)

In [95]:
test_df = pipe.transform(test_df)

In [96]:
test_df

array([[-0.49078316061772326, 1.0, 0.0, ..., 3, 0, 0],
       [-0.5074788432328381, 0.0, 1.0, ..., 3, 1, 0],
       [-0.4533668714188957, 1.0, 0.0, ..., 2, 0, 0],
       ...,
       [-0.5024451714361923, 0.0, 1.0, ..., 3, 0, 0],
       [-0.4863374216869257, 0.0, 1.0, ..., 3, 0, 0],
       [-0.19824427701513722, 0.0, 0.0, ..., 3, 1, 1]], dtype=object)

In [97]:
dt = DecisionTreeClassifier()

In [98]:
dt.fit(train_df, y_train)

DecisionTreeClassifier()

In [99]:
y_pred = dt.predict(test_df)

In [100]:
from sklearn.metrics import accuracy_score

In [101]:
y_test = pd.read_csv('gender_submission.csv')

In [103]:
y_test

PassengerId  Survived
0            892         0
1            893         1
2            894         0
3            895         0
4            896         1
..           ...       ...
413         1305         0
414         1306         1
415         1307         0
416         1308         0
417         1309         0

[418 rows x 2 columns]

In [108]:
accuracy_score(y_pred, y_test['Survived'])

0.7990430622009569

In [109]:
submission = pd.DataFrame({
    'PassengerId': y_test['PassengerId'],  # Replace with your actual test DataFrame
    'Survived': y_pred
})

In [110]:
submission.to_csv('submission.csv', index=False)